''' This file contains various settings for use with S3 '''

S3_CREATE_BUCKET_FAILED = 0
S3_CREATE_BUCKET_SUCCESS = 1
S3_BUCKET_ALREADY_EXISTS = 2
S3_BUCKET_DELETE_SUCCESS = 3
S3_BUCKET_DELETE_FAILED = 4
S3_PUT_OBJECT_SUCCESS = 5
S3_PUT_OBJECT_FAIL = 6
